[package]
name = "wallflower"
version = "0.1.0"
authors = ["Wesley Moore <wes@wezm.net>"]

[dependencies]
bytes = "0.4"
futures = "0.1"
env_logger = "*"

reqwest = "*"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
json = "*"

actix = "0.7"
actix-web = "^0.7"
